# enable labeler on issues, prs, or both.
enable:
  issues: false
  prs: true

# 레이블을 성공적으로 붙이고 PR에 보낼 코멘트를 설정
comments:
  prs: |
    Labeler has applied any labels matching special text in your title and description.
    Please review the labels and make any necessary changes.

# 라벨 규칙 설정
'🖌️ assets':
  head-branch: ['^feature/assets']
'🎊 breaking change':
  head-branch: ['^feature/breaking-change']
'🐞 bug':
  head-branch: ['^bugfix/']
'🧱 build':
  head-branch: ['^build/']
'🧹 chore':
  head-branch: ['^chore/']
'🤖 ci':
  head-branch: ['^ci/']
'🎨 design':
  head-branch: ['^design/']
'📓 documentation':
  head-branch: ['^docs/']
'✨ feature':
  head-branch: ['^feature/']
'⚡ performance':
  head-branch: ['^perf/']
'🏗️ refactor':
  head-branch: ['^refactor/']
'🗑️ remove':
  head-branch: ['^remove/']
'✍️ rename':
  head-branch: ['^rename/']
'💈 style':
  head-branch: ['^style/']
