enable:
  issues: false
  prs: true

labels:
  '🖌️ assets':
    include:
      - '\bassets\b'
  '🎊 breaking change':
    include:
      - '\bbreaking change\b'
  '🐞 bug':
    include:
      - '\bbug\b'
  '🧱 build':
    include:
      - '\bbuild\b'
  '🧹 chore':
    include:
      - '\bchore\b'
  '🤖 ci':
    include:
      - '\bci\b'
  '🎨 design':
    include:
      - '\bdesign\b'
  '📓 documentation':
    include:
      - '\bdocs\b'
  '✨ feature':
    include:
      - '\bfeat\b'
  '⚡ performance':
    include:
      - '\bperf\b'
  '🏗️ refactor':
    include:
      - '\brefactor\b'
  '🗑️ remove':
    include:
      - '\bremove\b'
  '✍️ rename':
    include:
      - '\brename\b'
  '💈 style':
    include:
      - '\bstyle\b'
