import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
  name: "Projects",
  projects: [
    "Projects/**"
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
